const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_SUCCESS';
const GET_PUBLICATIONS_ERROR = 'GET_PUBLICATIONS_ERROR';

export { GET_PUBLICATIONS, GET_PUBLICATIONS_SUCCESS, GET_PUBLICATIONS_ERROR };
