const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_SUCCESS';
const GET_PUBLICATIONS_ERROR = 'GET_PUBLICATIONS_ERROR';
const GET_USER_PUBLICATION_SUCCESS = 'GET_USER_PUBLICATION_SUCCESS';
const GET_USER_PUBLICATION_ERROR = 'GET_USER_PUBLICATION_ERROR';
const OPEN_CLOSE_USER_PUBLICATION = 'OPEN_CLOSE_USER_PUBLICATION';
const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
const GET_POST_COMMENTS_ERROR = 'GET_POST_COMMENTS_SUCCESS';

export {
  GET_PUBLICATIONS,
  GET_PUBLICATIONS_SUCCESS,
  GET_PUBLICATIONS_ERROR,
  GET_USER_PUBLICATION_SUCCESS,
  GET_USER_PUBLICATION_ERROR,
  OPEN_CLOSE_USER_PUBLICATION,
  GET_POST_COMMENTS,
  GET_POST_COMMENTS_SUCCESS,
  GET_POST_COMMENTS_ERROR,
};
