const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_SUCCESS';
const GET_PUBLICATIONS_ERROR = 'GET_PUBLICATIONS_ERROR';
const GET_USER_PUBLICATION_SUCCESS = 'GET_USER_PUBLICATION_SUCCESS';
const GET_USER_PUBLICATION_ERROR = 'GET_USER_PUBLICATION_ERROR';

export {
  GET_PUBLICATIONS,
  GET_PUBLICATIONS_SUCCESS,
  GET_PUBLICATIONS_ERROR,
  GET_USER_PUBLICATION_SUCCESS,
  GET_USER_PUBLICATION_ERROR,
};
